rye run gm-train \
    --dataset  "/home/jlagesse/gnnco/data/ER[100,8,0.12]" \
    --experiment "GAT ER[100,8,_]" \
    --run-name "Large GAT ER[100,8,0.12]" \
    --epochs 500 \
    --batch-size 100 \
    --cuda \
    --log-frequency 10 \
    --no-profile \
    --model GAT \
        --layers 8 \
        --heads 8 \
        --features 256 \
        --out-features 64 \
    --optimizer adam-one-cycle \
        --max-lr 3e-3 \
        --start-factor 5 \
        --end-factor 500 \
        --grad-clip 0.1