rye run gnnco-train siamese-gm \
    --dataset  "/scratch/jlagesse/gnnco/datasets/ER[100,8,0.12]" \
    --experiment "BETA Test" \
    --run-name "BETA_0.001 GCN" \
    --beta 0.001 \
    --epochs 1000 \
    --batch-size 50 \
    --cuda \
    --log-frequency 25 \
    --no-profile \
    --model GCN \
        --layers 5 \
        --features 128 \
        --out-features 128 \
    --optimizer adam-one-cycle \
        --max-lr 1e-3 \
        --start-factor 5 \
        --end-factor 500 \
        --grad-clip 1