rye run gm-train \
    --dataset  "/home/jlagesse/gnnco/data/ER[100,8,0.18]" \
    --experiment "NEW LIBRARY" \
    --run-name "ER[100,8,0.18]" \
    --epochs 500 \
    --batch-size 250 \
    --cuda \
    --log-frequency 10 \
    --no-profile \
    --model GAT \
        --layers 4 \
        --heads 8 \
        --features 64 \
        --out-features 64 \
    --optimizer adam-one-cycle \
        --max-lr 8e-4 \
        --start-factor 5 \
        --end-factor 500 \
        --grad-clip 0.1